/* font.h - bitmap console font. */
#pragma once

extern const int font_width;
extern const int font_height;
extern const unsigned char font_glyphs[128][16];
/* 0x80-0xFF: the box-drawing/block/symbol glyphs a TUI needs, generated by
 * tools/genfont.py into kernel/fontext.c (M2015). Kept as a second array
 * rather than widening font_glyphs so SYS_font's 2048-byte ABI is unchanged. */
extern const unsigned char font_ext[128][16];
unsigned char font_cp_to_glyph(unsigned long cp);   /* Unicode -> the byte the grid stores; 0 = drop */
/* The 16 rows of whichever table `c` belongs to. Never NULL. */
static inline const unsigned char *font_row(unsigned char c) {
    return (c < 128) ? font_glyphs[c] : font_ext[c - 128];
}
