#ifndef XKBMAP_H
#define XKBMAP_H
/* OS-DEV's own XKB keymap -- the US layout, written by hand for this project.
 *
 * Wayland's `wl_keyboard.keymap` event does not carry key LABELS; it carries a
 * file descriptor to a keymap that the client compiles with libxkbcommon, and
 * a client that never receives one cannot turn a keycode into a character at
 * all. GTK (and therefore Firefox) will take no text input without it.
 *
 * It is deliberately SELF-CONTAINED: no `include "complete"`, so it compiles
 * with XKB_CONTEXT_NO_DEFAULT_INCLUDES and needs none of the /usr/share/X11/xkb
 * data files present in the guest. Everything here -- keycodes, types, compat
 * interpretations and symbols -- is spelled out.
 *
 * XKB keycodes are evdev keycodes + 8, which is why `a` (evdev 30) is <AC01> =
 * 38. That offset is historical (X11 reserved 0-7) and is not optional: a
 * keymap written at the evdev numbering silently produces the wrong character
 * for every key.
 *
 * tests/run-xkb-tests.sh compiles this exact string with the real libxkbcommon
 * and checks the characters that come out, so it cannot rot silently. (M1984)
 */
static const char osdev_xkb_keymap[] =
    "xkb_keymap {\n"
    "xkb_keycodes \"osdev\" {\n"
    "    minimum = 8;\n"
    "    maximum = 255;\n"
    "    <ESC>  =   9;\n"
    "    <AE01> =  10; <AE02> =  11; <AE03> =  12; <AE04> =  13; <AE05> =  14;\n"
    "    <AE06> =  15; <AE07> =  16; <AE08> =  17; <AE09> =  18; <AE10> =  19;\n"
    "    <AE11> =  20; <AE12> =  21; <BKSP> =  22; <TAB>  =  23;\n"
    "    <AD01> =  24; <AD02> =  25; <AD03> =  26; <AD04> =  27; <AD05> =  28;\n"
    "    <AD06> =  29; <AD07> =  30; <AD08> =  31; <AD09> =  32; <AD10> =  33;\n"
    "    <AD11> =  34; <AD12> =  35; <RTRN> =  36; <LCTL> =  37;\n"
    "    <AC01> =  38; <AC02> =  39; <AC03> =  40; <AC04> =  41; <AC05> =  42;\n"
    "    <AC06> =  43; <AC07> =  44; <AC08> =  45; <AC09> =  46; <AC10> =  47;\n"
    "    <AC11> =  48; <TLDE> =  49; <LFSH> =  50; <BKSL> =  51;\n"
    "    <AB01> =  52; <AB02> =  53; <AB03> =  54; <AB04> =  55; <AB05> =  56;\n"
    "    <AB06> =  57; <AB07> =  58; <AB08> =  59; <AB09> =  60; <AB10> =  61;\n"
    "    <RTSH> =  62; <KPMU> =  63; <LALT> =  64; <SPCE> =  65; <CAPS> =  66;\n"
    "    <FK01> =  67; <FK02> =  68; <FK03> =  69; <FK04> =  70; <FK05> =  71;\n"
    "    <FK06> =  72; <FK07> =  73; <FK08> =  74; <FK09> =  75; <FK10> =  76;\n"
    "    <NMLK> =  77; <SCLK> =  78;\n"
    "    <KP7>  =  79; <KP8>  =  80; <KP9>  =  81; <KPSU> =  82;\n"
    "    <KP4>  =  83; <KP5>  =  84; <KP6>  =  85; <KPAD> =  86;\n"
    "    <KP1>  =  87; <KP2>  =  88; <KP3>  =  89; <KP0>  =  90; <KPDL> =  91;\n"
    "    <FK11> =  95; <FK12> =  96;\n"
    "    <KPEN> = 104; <RCTL> = 105; <KPDV> = 106; <PRSC> = 107; <RALT> = 108;\n"
    "    <HOME> = 110; <UP>   = 111; <PGUP> = 112; <LEFT> = 113; <RGHT> = 114;\n"
    "    <END>  = 115; <DOWN> = 116; <PGDN> = 117; <INS>  = 118; <DELE> = 119;\n"
    "    <LWIN> = 133; <RWIN> = 134; <COMP> = 135;\n"
    "};\n"
    "\n"
    "xkb_types \"osdev\" {\n"
    "    virtual_modifiers NumLock,Alt,LevelThree;\n"
    "    type \"ONE_LEVEL\" {\n"
    "        modifiers = none;\n"
    "        map[none] = Level1;\n"
    "        level_name[Level1] = \"Any\";\n"
    "    };\n"
    "    type \"TWO_LEVEL\" {\n"
    "        modifiers = Shift;\n"
    "        map[none]  = Level1;\n"
    "        map[Shift] = Level2;\n"
    "        level_name[Level1] = \"Base\";\n"
    "        level_name[Level2] = \"Shift\";\n"
    "    };\n"
    "    type \"ALPHABETIC\" {\n"
    "        modifiers = Shift+Lock;\n"
    "        map[none]       = Level1;\n"
    "        map[Shift]      = Level2;\n"
    "        map[Lock]       = Level2;\n"
    "        map[Shift+Lock] = Level1;\n"
    "        level_name[Level1] = \"Base\";\n"
    "        level_name[Level2] = \"Caps\";\n"
    "    };\n"
    "    type \"KEYPAD\" {\n"
    "        modifiers = Shift+NumLock;\n"
    "        map[none]           = Level1;\n"
    "        map[Shift]          = Level2;\n"
    "        map[NumLock]        = Level2;\n"
    "        map[Shift+NumLock]  = Level1;\n"
    "        level_name[Level1] = \"Base\";\n"
    "        level_name[Level2] = \"Number\";\n"
    "    };\n"
    "};\n"
    "\n"
    "xkb_compatibility \"osdev\" {\n"
    "    virtual_modifiers NumLock,Alt,LevelThree;\n"
    "    interpret.useModMapMods = AnyLevel;\n"
    "    interpret.repeat = False;\n"
    "    interpret Any+AnyOf(all) {\n"
    "        action = SetMods(modifiers=modMapMods,clearLocks);\n"
    "    };\n"
    "    interpret Caps_Lock+AnyOf(all) {\n"
    "        action = LockMods(modifiers=Lock);\n"
    "    };\n"
    "    interpret Num_Lock+AnyOf(all) {\n"
    "        virtualModifier = NumLock;\n"
    "        action = LockMods(modifiers=NumLock);\n"
    "    };\n"
    "    interpret Alt_L+AnyOf(all) {\n"
    "        virtualModifier = Alt;\n"
    "        action = SetMods(modifiers=modMapMods,clearLocks);\n"
    "    };\n"
    "    interpret Alt_R+AnyOf(all) {\n"
    "        virtualModifier = Alt;\n"
    "        action = SetMods(modifiers=modMapMods,clearLocks);\n"
    "    };\n"
    "};\n"
    "\n"
    "xkb_symbols \"osdev\" {\n"
    "    name[Group1] = \"OS-DEV US\";\n"
    "\n"
    "    key <ESC>  { [ Escape ] };\n"
    "    key <AE01> { [ 1, exclam ] };\n"
    "    key <AE02> { [ 2, at ] };\n"
    "    key <AE03> { [ 3, numbersign ] };\n"
    "    key <AE04> { [ 4, dollar ] };\n"
    "    key <AE05> { [ 5, percent ] };\n"
    "    key <AE06> { [ 6, asciicircum ] };\n"
    "    key <AE07> { [ 7, ampersand ] };\n"
    "    key <AE08> { [ 8, asterisk ] };\n"
    "    key <AE09> { [ 9, parenleft ] };\n"
    "    key <AE10> { [ 0, parenright ] };\n"
    "    key <AE11> { [ minus, underscore ] };\n"
    "    key <AE12> { [ equal, plus ] };\n"
    "    key <BKSP> { [ BackSpace ] };\n"
    "    key <TAB>  { [ Tab, ISO_Left_Tab ] };\n"
    "    key <AD01> { [ q, Q ] };\n"
    "    key <AD02> { [ w, W ] };\n"
    "    key <AD03> { [ e, E ] };\n"
    "    key <AD04> { [ r, R ] };\n"
    "    key <AD05> { [ t, T ] };\n"
    "    key <AD06> { [ y, Y ] };\n"
    "    key <AD07> { [ u, U ] };\n"
    "    key <AD08> { [ i, I ] };\n"
    "    key <AD09> { [ o, O ] };\n"
    "    key <AD10> { [ p, P ] };\n"
    "    key <AD11> { [ bracketleft, braceleft ] };\n"
    "    key <AD12> { [ bracketright, braceright ] };\n"
    "    key <RTRN> { [ Return ] };\n"
    "    key <LCTL> { [ Control_L ] };\n"
    "    key <AC01> { [ a, A ] };\n"
    "    key <AC02> { [ s, S ] };\n"
    "    key <AC03> { [ d, D ] };\n"
    "    key <AC04> { [ f, F ] };\n"
    "    key <AC05> { [ g, G ] };\n"
    "    key <AC06> { [ h, H ] };\n"
    "    key <AC07> { [ j, J ] };\n"
    "    key <AC08> { [ k, K ] };\n"
    "    key <AC09> { [ l, L ] };\n"
    "    key <AC10> { [ semicolon, colon ] };\n"
    "    key <AC11> { [ apostrophe, quotedbl ] };\n"
    "    key <TLDE> { [ grave, asciitilde ] };\n"
    "    key <LFSH> { [ Shift_L ] };\n"
    "    key <BKSL> { [ backslash, bar ] };\n"
    "    key <AB01> { [ z, Z ] };\n"
    "    key <AB02> { [ x, X ] };\n"
    "    key <AB03> { [ c, C ] };\n"
    "    key <AB04> { [ v, V ] };\n"
    "    key <AB05> { [ b, B ] };\n"
    "    key <AB06> { [ n, N ] };\n"
    "    key <AB07> { [ m, M ] };\n"
    "    key <AB08> { [ comma, less ] };\n"
    "    key <AB09> { [ period, greater ] };\n"
    "    key <AB10> { [ slash, question ] };\n"
    "    key <RTSH> { [ Shift_R ] };\n"
    "    key <KPMU> { [ KP_Multiply ] };\n"
    "    key <LALT> { [ Alt_L ] };\n"
    "    key <SPCE> { [ space ] };\n"
    "    key <CAPS> { [ Caps_Lock ] };\n"
    "    key <FK01> { [ F1 ] };\n"
    "    key <FK02> { [ F2 ] };\n"
    "    key <FK03> { [ F3 ] };\n"
    "    key <FK04> { [ F4 ] };\n"
    "    key <FK05> { [ F5 ] };\n"
    "    key <FK06> { [ F6 ] };\n"
    "    key <FK07> { [ F7 ] };\n"
    "    key <FK08> { [ F8 ] };\n"
    "    key <FK09> { [ F9 ] };\n"
    "    key <FK10> { [ F10 ] };\n"
    "    key <FK11> { [ F11 ] };\n"
    "    key <FK12> { [ F12 ] };\n"
    "    key <NMLK> { [ Num_Lock ] };\n"
    "    key <SCLK> { [ Scroll_Lock ] };\n"
    "    key <KP7>  { type=\"KEYPAD\", [ KP_Home,  KP_7 ] };\n"
    "    key <KP8>  { type=\"KEYPAD\", [ KP_Up,    KP_8 ] };\n"
    "    key <KP9>  { type=\"KEYPAD\", [ KP_Prior, KP_9 ] };\n"
    "    key <KPSU> { [ KP_Subtract ] };\n"
    "    key <KP4>  { type=\"KEYPAD\", [ KP_Left,  KP_4 ] };\n"
    "    key <KP5>  { type=\"KEYPAD\", [ KP_Begin, KP_5 ] };\n"
    "    key <KP6>  { type=\"KEYPAD\", [ KP_Right, KP_6 ] };\n"
    "    key <KPAD> { [ KP_Add ] };\n"
    "    key <KP1>  { type=\"KEYPAD\", [ KP_End,   KP_1 ] };\n"
    "    key <KP2>  { type=\"KEYPAD\", [ KP_Down,  KP_2 ] };\n"
    "    key <KP3>  { type=\"KEYPAD\", [ KP_Next,  KP_3 ] };\n"
    "    key <KP0>  { type=\"KEYPAD\", [ KP_Insert, KP_0 ] };\n"
    "    key <KPDL> { type=\"KEYPAD\", [ KP_Delete, KP_Decimal ] };\n"
    "    key <KPEN> { [ KP_Enter ] };\n"
    "    key <RCTL> { [ Control_R ] };\n"
    "    key <KPDV> { [ KP_Divide ] };\n"
    "    key <PRSC> { [ Print ] };\n"
    "    key <RALT> { [ Alt_R ] };\n"
    "    key <HOME> { [ Home ] };\n"
    "    key <UP>   { [ Up ] };\n"
    "    key <PGUP> { [ Prior ] };\n"
    "    key <LEFT> { [ Left ] };\n"
    "    key <RGHT> { [ Right ] };\n"
    "    key <END>  { [ End ] };\n"
    "    key <DOWN> { [ Down ] };\n"
    "    key <PGDN> { [ Next ] };\n"
    "    key <INS>  { [ Insert ] };\n"
    "    key <DELE> { [ Delete ] };\n"
    "    key <LWIN> { [ Super_L ] };\n"
    "    key <RWIN> { [ Super_R ] };\n"
    "    key <COMP> { [ Menu ] };\n"
    "\n"
    "    modifier_map Shift   { <LFSH>, <RTSH> };\n"
    "    modifier_map Lock    { <CAPS> };\n"
    "    modifier_map Control { <LCTL>, <RCTL> };\n"
    "    modifier_map Mod1    { <LALT>, <RALT> };\n"
    "    modifier_map Mod2    { <NMLK> };\n"
    "    modifier_map Mod4    { <LWIN>, <RWIN> };\n"
    "};\n"
    "};\n"
    "\n"
;

#endif /* XKBMAP_H */
