#!/bin/sh
# Re-apply PERSISTENT GUEST STATE to a freshly built ext2 image (M2040).
#
# build/ext2.img is a build artifact: it depends on $(LXBINS), so `make check`,
# `make lxtooltest` and anything else that touches a staged binary REBUILDS it
# from scratch with mke2fs. Anything that was only ever inside the image is
# destroyed. That has cost an in-guest Claude Code login three times -- a login
# that requires a human to complete an OAuth flow inside the VM and therefore
# cannot be regenerated by any script.
#
# So the state lives in a HOST directory OUTSIDE the repo, and this puts it
# back. The directory mirrors the guest layout:
#
#   <state>/root/.claude/...     credentials, settings, session history
#   <state>/src/.git/...         a real git repo for the in-guest source tree
#   <state>/usr/bin/...          extra borrowed tools (grep, ps, sed, ...)
#   <state>/bin/...              the /bin aliases a Linux program execs
#
# It is deliberately NOT in the repo and deliberately not committed: it holds
# real credentials. Keep it in a scratch or home directory and point STATE_DIR
# at it.
#
# usage: inject-guest-state.sh <state-dir> [image]
set -e
STATE="$1"
IMG="${2:-build/ext2.img}"
[ -n "$STATE" ] || { echo "usage: $0 <state-dir> [image]" >&2; exit 2; }
[ -d "$STATE" ] || { echo "$0: no such state dir: $STATE" >&2; exit 2; }
[ -f "$IMG" ]   || { echo "$0: no such image: $IMG" >&2; exit 2; }
command -v debugfs >/dev/null 2>&1 || { echo "$0: needs debugfs (e2fsprogs)" >&2; exit 2; }

# Directories first, shallowest to deepest, so a child never precedes its parent.
(cd "$STATE" && find . -type d ! -name . | sed 's|^\./||' | awk '{print gsub(/\//,"/"), $0}' | sort -n | cut -d" " -f2-) |
while IFS= read -r d; do
    debugfs -w -R "mkdir /$d" "$IMG" >/dev/null 2>&1 || true
done

n=0
(cd "$STATE" && find . -type f | sed 's|^\./||') |
while IFS= read -r f; do
    debugfs -w -R "rm /$f" "$IMG" >/dev/null 2>&1 || true
    debugfs -w -R "write $STATE/$f /$f" "$IMG" >/dev/null 2>&1 || {
        echo "  WARN could not inject /$f" >&2; continue; }
    n=$((n + 1))
done

files=$(cd "$STATE" && find . -type f | wc -l)
echo "  INJECT  $files file(s) of guest state from $STATE into $IMG"
# Report the two that matter, by name, so a silent partial restore is visible.
for probe in /root/.claude/.credentials.json /src/.git/HEAD; do
    if debugfs -R "stat $probe" "$IMG" 2>/dev/null | grep -q '^Inode:'; then
        echo "  ok      $probe"
    else
        echo "  MISSING $probe -- the state dir does not have it" >&2
    fi
done
